version: "3.4"
services:
  grafana:
    build: ./grafana
    restart: always
    volumes:
      - "prometheus:/prometheus"
  prometheus:
    buiĺd: ./prometheus
    restart: always
    volumes:
      - "prometheus:/prometheus"
      - "provisioning:/provisioning/"
  manager:
    build: ./manager
    restart: always
    volumes:
      - "provisioning:/provisioning/"
volumes:
  grafana: {}
  prometheus: {}
  provisioning: {}
