version: "3.4"
services:
  grafana:
    build: ./grafana
    restart: always
    volumes:
      - "grafana_data:/var/lib/grafana"
  prometheus:
    build: ./prometheus
    restart: always
    volumes:
      - "prometheus_data:/prometheus"
      - "prometheus_file_sd:/prometheus_file_sd"
  manager:
    build: ./manager
    restart: always
    volumes:
      - "manager_data:/data"
      - "prometheus_file_sd:/prometheus_file_sd"
volumes:
  grafana_data: {}
  prometheus_data: {}
  manager_data: {}
  prometheus_file_sd: {}
