version: "3.4"
services:
  grafana:
    build: ./grafana
    restart: always
    volumes:
      - "prometheus:/prometheus"
  prometheus:
    build: ./prometheus
    restart: always
    volumes:
      - "prometheus:/prometheus"
      - "prometheus_file_sd:/prometheus_file_sd"
  manager:
    build: ./manager
    restart: always
    volumes:
      - "manager:/data"
      - "prometheus_file_sd:/prometheus_file_sd"
volumes:
  grafana: {}
  prometheus: {}
  manager: {}
  prometheus_file_sd: {}
