scrape_configs:
  # Files copied programatically by the manager container
  - job_name: "manager_sd"
    scrape_interval: 10s
    file_sd_configs:
      - files:
          - /prometheus_file_sd/*.yml
          - /prometheus_file_sd/*.json
