name: "Main"
on:
  pull_request:
  push:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"

jobs:
  manager-tests:
    runs-on: ubuntu-16.04
    name: Manager tests
    defaults:
      run:
        working-directory: ./manager
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn
      - run: yarn test

  build-test:
    runs-on: ubuntu-16.04
    name: Build test
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v2
      - run: npx @dappnode/dappnodesdk build --skip_save

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [manager-tests]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --dappnode_team_preset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
